### ISSUE TITLE
psycopg2 or psycopg2-binary 

### ISSUE THREAD

**Issue by vincentsarago** [stac-utils/titiler-pgstac#12]
In the requirements we ask for `psycopg2` which will be usually fine if you install titiler-pgstac on an environment where you have PG installed but it can be difficult in light environments like AWS Lambda where you would prefer installing `psycopg2-binary`

https://github.com/stac-utils/titiler-pgstac/blob/84ebde28afbdcdb128537436438902869f54f17a/setup.py#L12

See https://github.com/developmentseed/eoAPI/blob/master/deployment/dockerfiles/Dockerfile.raster#L3-L14 (basically I had to install PG, install titiler-pgstac, remove psycopg2 files and then install `psycopg2-binary`

I'm not sure what's the best way to have option to install either `psycopg2` or `psycopg2-binary` 🤷‍♂️

**Comment by kylebarron** [comment]
A couple notes: 

The `psycopg2-binary` package [says](https://pypi.org/project/psycopg2-binary/):

> The binary package is a practical choice for development and testing but in production it is advised to use the package built from sources

One option is to require the end user to choose, by not installing either dependency with the base bundle, then having `titiler.pgstac[psycopg2]` and `titiler.pgstac[psycopg2-binary]` extras

**Comment by vincentsarago** [comment]
🙏 thanks @kylebarron 

I kinda like the `environment variable` approach as in https://github.com/dbt-labs/dbt/blob/45fe76eef4b4b82ae1442f00310e0c6a121774f2/plugins/postgres/setup.py#L22-L73

**Comment by kylebarron** [comment]
That's cool. I like that. On the flip side... what happens if you install both packages? Which takes precedence? I think the environment variable approach gets annoying if you become a dependency of another package and then the env var switching isn't obvious. 🤷‍♂️ 

It would be kinda nice if you could install both packages and then the non-binary would take preference.

**Comment by vincentsarago** [comment]
I'm not sure about precedence. I think the safest way for now is to remove `psycopg2` and add a note in the Readme.
