### ISSUE TITLE
morecantile 5.1 breaks /map endpoint

### ISSUE THREAD

**Issue by hrodmn** [stac-utils/titiler-pgstac#147]
The [most recent version of `morcantile`](https://github.com/developmentseed/morecantile/blob/main/CHANGES.md#510-2024-01-08) breaks the `/map` endpoint because the `_resolution` method was removed. I was able to patch it in my deployment by pinning to `morcantile>=5.0,<5.1`, but we probably need to replace the usage of the `TileMatrixSet._resolution` method with something else.

https://github.com/stac-utils/titiler-pgstac/blob/1.0.0/titiler/pgstac/factory.py#L439

I think this is an issue in `titiler`, too:
https://github.com/developmentseed/titiler/blob/0.16.0/src/titiler/mosaic/titiler/mosaic/factory.py#L508

**Comment by vincentsarago** [comment]
Oh no 😭 
I'll fix this in titiler and then prepare something for titiler-pgstac

**Comment by vincentsarago** [comment]
the fix is to do 
```
"resolutions": [matrix.cellSize for matrix in tms],
```
