### ISSUE TITLE
add more parameters to the Collection Endpoints 

### ISSUE THREAD

**Issue by vincentsarago** [stac-utils/titiler-pgstac#159]
We can add simple parameters like:
- ids
- datetime
- bbox

like https://github.com/developmentseed/titiler-stacapi/blob/0a558ade45c06aa4e0f4f5dd71ea3212e8671d9a/titiler/stacapi/dependencies.py#L116-L164

**Comment by hrodmn** [comment]
Did you consider adding `filter` as a parameter in addition to `bbox`, `datetime`, and `ids`? I can think of a few contexts where adding a cql2-text filter would be useful.

**Comment by vincentsarago** [comment]
Can you open a new issue with that 🙏
