### ISSUE TITLE
Missing / incomplete tiles where rasters' valid data borders each other

### ISSUE THREAD

**Issue by zstatmanweil** [stac-utils/titiler-pgstac#180]
I am working with rasters that correspond to watersheds and so have valid data within these boundaries and nodata without. When Rasters are float32, 5m resolution. I view them with `titiler-pgstac` at zoom 11, I have no issues:

![image](https://github.com/user-attachments/assets/3a19c147-e5dc-463d-9d9f-19c56a3ab9ff)

When I zoom in, I start seeing oddities like here you can see the tile is only filled in by one of the watersheds values:

![image](https://github.com/user-attachments/assets/61371a8a-2ff1-4c7e-a9c6-bd1314aea76e)

I zoom in more and some tiles are completely missing data:
![image](https://github.com/user-attachments/assets/cf6c2f76-9f77-4be6-aa29-ecc13facdf96)

I tried to play around with `pixel_selection`, `resampling` and `scale` but the same issue occurred in the same places. 

I am a little unclear on which DEBUG env variable name I should use so I tried all three of these but none seemed to actually show any logs:
      - DEBUG=TRUE
      - TITILER_DEBUG=TRUE
      - TITILER_PGSTAC_API_DEBUG=TRUE

Any pointers on troubleshooting would be much appreciated!

**Comment by drnextgis** [comment]
If you use titiler-pgstac which comes with eoAPI then to enable DEBUG you should use `EOAPI_RASTER_DEBUG`.

**Comment by zstatmanweil** [comment]
Thanks @drnextgis, I am not running via eoAPI though

**Comment by zstatmanweil** [comment]
When I set both `exitwhenfull` and `skipcovered` to False, I no longer have this issue. I think I was assuming it would factor in the nodata value but since those parameters are used on the pgstac side, it makes sense it is just looking at the geometry, not assessing the raster or its nodata value. 

No issues here!
