### ISSUE TITLE
Filtering by id doesn't work

### ISSUE THREAD

**Issue by drnextgis** [stac-utils/titiler-pgstac#37]
Create a search by providing a list of ids:

```
$ curl -s -X 'POST' \
  'http://0.0.0.0:8081/register' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "ids": [
    "newsat20_micro_L1_a6862829-8f18-4ac3-9e71-3d7be4bff1f3_0_40_1_3_3",
    "newsat20_micro_L1_a6862829-8f18-4ac3-9e71-3d7be4bff1f3_0_40_1_3_4"
  ]
}' | jq
{
  "searchid": "31e80bcee45da399dddad8d97b79e9da",
  "metadata": "http://0.0.0.0:8081/31e80bcee45da399dddad8d97b79e9da/info",
  "tiles": "http://0.0.0.0:8081/31e80bcee45da399dddad8d97b79e9da/tilejson.json"
}
```

Check the search info:

```
curl -s -X 'GET' \
  'http://0.0.0.0:8081/31e80bcee45da399dddad8d97b79e9da/info' \
  -H 'accept: application/json' | jq
{
  "hash": "31e80bcee45da399dddad8d97b79e9da",
  "search": {
    "ids": [
      "newsat20_micro_L1_a6862829-8f18-4ac3-9e71-3d7be4bff1f3_0_40_1_3_3",
      "newsat20_micro_L1_a6862829-8f18-4ac3-9e71-3d7be4bff1f3_0_40_1_3_4"
    ]
  },
  "_where": " TRUE ",
  "orderby": "datetime DESC, id DESC",
  "lastused": "2022-02-18T00:47:56.524663+00:00",
  "usecount": 5,
  "metadata": {}
}
```

Check the assets by the given searchid:

```
$ curl -s -X 'GET' \
  'http://0.0.0.0:8081/31e80bcee45da399dddad8d97b79e9da/-42.0,-12.7/assets' \
  -H 'accept: application/json' | jq ".[0].id"
"newsat20_micro_L1_a6862829-8f18-4ac3-9e71-3d7be4bff1f3_0_40_1_0_10"
```

As you can see I get an asset which doesn't meet the search criteria. I understand that it is probably connected with switching to cql2 (I use pgstac v0.4.5) but then it would be good have it mentioned in the docs.

**Comment by vincentsarago** [comment]
I think this is the same as https://github.com/stac-utils/stac-fastapi/pull/346

**Comment by drnextgis** [comment]
I use latest version of PGStac 0.4.5 or do you mean it requires changes on titiler-pgstac side?

**Comment by vincentsarago** [comment]
>  do you mean it requires changes on titiler-pgstac side?

I think yes, but I need to go through the PR to see what changes are required for the filter-lang. Or we could only support the cql filter 😄

**Comment by vincentsarago** [comment]
added tests in https://github.com/stac-utils/titiler-pgstac/commit/e63e3507f1899c0fe053d7ff466afd378d2ddf5d and couldn't reproduce
