### ISSUE TITLE
How to select predefined visualisations as stored in 'defaults' metadata

### ISSUE THREAD

**Issue by robintw** [stac-utils/titiler-pgstac#64]
The metadata configuration described [here](https://stac-utils.github.io/titiler-pgstac/advanced/metadata/) allows you to specify a list of default visualisation configurations in a `defaults` entry - eg:

```
 // OPTIONAL. Default: null. A set of `defaults` configuration to be forwarded to the /tiles endpoints.
    "defaults": {
        "true_color": {
            "assets": ["B4", "B3", "B2"],
            "color_formula": "Gamma RGB 3.5 Saturation 1.7 Sigmoidal RGB 15 0.35",
        },
        "ndvi": {
            "expression": "(B4-B3)/(B4+B3)",
            "rescale": "-1,1",
            "colormap_name": "viridis"
        }
    }
```

Is there a way to pass the name of one of these defaults to one of the tiles endpoints, to get that visualisation automatically? This seems to be the purpose of this feature, but I can't actually find any way to do this - is it not yet implemented?

**Comment by vincentsarago** [comment]
created an example in https://github.com/stac-utils/titiler-pgstac/blob/dc3cde37f0141e1c659264b3168a9e9d7098a7bc/docs/advanced/custom_tilejson.md

as said, the `metadata` has an open format and it might be quite complex to handle it by default. I hope the example can help you. 

feel free to re-open the issue if you feel we should do more @robintw
