### ISSUE TITLE
Repeated Error 4 /vsimem/path not recognised as a supported file format

### ISSUE THREAD

**Issue by robintw** [stac-utils/titiler-pgstac#69]
I'm running titiler-pgstac on an Azure App Service. I haven't had any problems before, but am now getting repeated errors in the logs that look like this:

```
ERROR 4: `/vsimem/f4758fe6-ed7e-4cee-a71c-8c20a778675f/f4758fe6-ed7e-4cee-a71c-8c20a778675f.tif' not recognized as a supported file format.
```

These are usually repeated multiple times, and seem to be related to performing a request for a tile. The tile request usually returns ok, though sometimes I get a 50x error (though I'm finding it hard to reproduce those).

I know I've provided very limited information here, but does anyone with more experience of the interaction of GDAL, rasterio and titiler-pgstac have any idea where these errors might be coming from, or where I should start looking?

I thought originally that my server might be running out of memory, but from the metrics I've checked that doesn't seem to be the case. I also wondered if this is some sort of threading issue, and that vsimem 'files' from one thread can't be read in another - and this is interacting with the ASGI interface somehow - but I've never experienced this before when running titiler-pgstac.

Any ideas to help with debugging would be very much appreciated!

**Comment by vincentsarago** [comment]
This errors can be ignored and is raised when we create the output image in https://github.com/cogeotiff/rio-tiler/blob/62b0371836b0cb116a53459b5a79fcdc84f1cab1/rio_tiler/utils.py#L491-L498

**Comment by vincentsarago** [comment]
@robintw here is the rasterio issue about the `error` https://github.com/rasterio/rasterio/issues/2339

> Is this a change that has happened recently? I haven't been getting these errors in the past.

I don't think

> Is there any way to suppress the errors in that code (some sort of rasterio context manager or something?) - I might have trouble getting these repeated errors past the QA people in my company when moving into production.

Those error are GDAL error (produced by rasterio), sadly I don't think we can remove them 🤷‍♂️

**Comment by vincentsarago** [comment]
@robintw this is not a titiler-pgstac or titiler issue (it's a rasterio one) so I'm going to close this here 🙏
