### ISSUE TITLE
Error using `expression` in mosaic tile endpoints

### ISSUE THREAD

**Issue by mmcfarland** [stac-utils/titiler-pgstac#79]
After upgrading to `0.2.2` and updating any use of `expression` option to include `asset_as_band=true` (or prefix with asset name), we're getting the following error:

```
"ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''"
```

This is only happening on `mosica/tiles` endpoints. The same options used on `item/preview.png` render without error.

Full trace is:

```
  File "/usr/local/lib/python3.9/site-packages/titiler/pgstac/factory.py", line 251, in tile
    content = image.render(
  File "/usr/local/lib/python3.9/site-packages/rio_tiler/models.py", line 675, in render
    return render(
  File "/usr/local/lib/python3.9/site-packages/rio_tiler/utils.py", line 430, in render
    mask = numpy.bitwise_and(alpha, mask)
TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Here's a few links (using both `asset_as_band` and prefix options) to the PC staging environment which has the behavior, and the same tile request in PC prod which doesn't:

- [Sentinel-2 NDVI (staging)](https://planetarycomputer-staging.microsoft.com/api/data/v1/mosaic/tiles/ee3c35fe2906b21590b2153418b89570/WebMercatorQuad/10/268/380@2x?asset_as_band=true&colormap_name=rdylgn&expression=%28B08-B04%29%2F%28B08%2BB04%29&nodata=0&rescale=-1%2C1&collection=sentinel-2-l2a&format=png)
- [Sentinel-2 NDVI (prod)](https://planetarycomputer.microsoft.com/api/data/v1/mosaic/tiles/ee3c35fe2906b21590b2153418b89570/WebMercatorQuad/10/268/380@2x?asset_as_band=true&colormap_name=rdylgn&expression=%28B08-B04%29%2F%28B08%2BB04%29&nodata=0&rescale=-1%2C1&collection=sentinel-2-l2a&format=png))
- [NAIP NDVI (staging)](https://planetarycomputer-staging.microsoft.com/api/data/v1/mosaic/tiles/f91b2853aa94968293f77702d0a481a8/WebMercatorQuad/12/1075/1521@2x?colormap_name=rdylgn&expression=%28image_b4-image_b1%29%2F%28image_b4%2Bimage_b1%29&rescale=-1%2C1&collection=naip&format=png)
- [NAIP NDVI (prod)](https://planetarycomputer.microsoft.com/api/data/v1/mosaic/tiles/f91b2853aa94968293f77702d0a481a8/WebMercatorQuad/12/1075/1521@2x?asset_expression=image%7C%28b4-b1%29%2F%28b4%2Bb1%29&assets=image&colormap_name=rdylgn&rescale=-1%2C1&collection=naip&format=png)

**Comment by vincentsarago** [comment]
It's a bug in rio-tiler, I can easily reproduce

```python
import numpy

mask = numpy.zeros((256,256), dtype="uint8")
alpha = numpy.zeros((256,256), dtype="float32")

numpy.bitwise_and(alpha, mask)
>> TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Will have a fix in rio-tiler soon

**Comment by vincentsarago** [comment]
This has been fixed in rio-tiler. A new version `4.1.8` is being published on pypi. a New deploy of your service should solve the issue @mmcfarland 

I'll let you close the issue if it's the case 🙏

**Comment by mmcfarland** [comment]
Fixed after deployment. Thanks for the quick turnaround!
