### ISSUE TITLE
unit tests not working on fork

### ISSUE THREAD

**Issue by ivica3730k** [stac-utils/titiler-pgstac#99]
Hi everyone. Sorry if this is a bit out of scope, but I've made a clean fork of this branch in my organisation and I can't get my 
unit tests to run successfully. Very weird considering it is the same code.

![image](https://github.com/stac-utils/titiler-pgstac/assets/17437897/9ff29e30-1b23-4a1b-84b8-419e66a35924)

https://github.com/SpatialDays/titiler-pgstac/tree/main

Would it be okay if I could ask you to re-run your tests, please?

Thanks!

Ivica

**Comment by vincentsarago** [comment]
confirmed, I guess some dependencies were updated and now broke the code 😓

**Comment by vincentsarago** [comment]
Sorry I didn't really had time today! 

The issue is because something changed with `pgstac` or `pypgstac` with the latest release 0.7.7 (last week)

cc @bitner (I'm not sure where/what yet)

**Comment by vincentsarago** [comment]
@bitner is it possible that `usecount` and `lastused` are now `None` when we add a `search` entry when using `search_query()` ?

**Comment by vincentsarago** [comment]
also it seems that passing the metadata has 0 influence 
https://github.com/stac-utils/titiler-pgstac/blob/d29a3247649753998cbf6fbb83e736169763afdc/titiler/pgstac/factory.py#L639-L645

meaning that the `search` returned won't have any metadata 🤷

**Comment by vincentsarago** [comment]
@ivica3730k for now you can run the CI and the application with a pgstac <0.7.7

**Comment by ivica3730k** [comment]
Thank you very much, I will lock it on my side then. Feel free to close the issue if that is it.

**Comment by vincentsarago** [comment]
Confirmed that with `0.7.7` breaking changes were introduced in the `pgstac.search_query` 

I've opened an issue in`pgstac` https://github.com/stac-utils/pgstac/issues/182

**Comment by vincentsarago** [comment]
🙏 thanks for the report @ivica3730k

David fixed pgstac, and now CI is 🟢

**Comment by ivica3730k** [comment]
Amazing!

Thank you guys!
